CREATE TABLE shop.product_audit (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id int NOT NULL,
  sku text NOT NULL,
  op text NOT NULL
);
CREATE FUNCTION shop.audit_product() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
  INSERT INTO shop.product_audit (product_id, sku, op)
  VALUES (NEW.id, NEW.sku, TG_OP);
  RETURN NEW;
END;
$fn$;
