CREATE TABLE aud_items (
  id int PRIMARY KEY,
  label text NOT NULL
);
CREATE TABLE aud_log (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id int NOT NULL,
  op text NOT NULL,
  label text NOT NULL
);
