/**
 * Opt-in bounded-parallel extraction (`ExtractOptions.concurrency`).
 *
 * The contract under test is EQUIVALENCE, not speed: N catalog-query streams
 * sharing the coordinator's `pg_export_snapshot()` must reproduce the serial
 * extraction byte-for-byte — same FactBase rootHash, same fact order, same edge
 * order, same diagnostics order — because the scheduler slots per-family results
 * by family index and merges in the fixed call order, never completion order.
 *
 * Everything else here is about not hurting anyone: never queue on an exhausted
 * pool (that would deadlock, since the coordinator holds a client while asking
 * for more), degrade silently to serial when the snapshot cannot be shared, and
 * leak no client / open transaction on any error path.
 */
import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import pg from "pg";
import type { Diagnostic } from "../src/core/diagnostic.ts";
import type { DependencyEdge, Fact } from "../src/core/fact.ts";
import {
  extract,
  ExtractionTimeoutError,
  type ExtractResult,
} from "../src/extract/extract.ts";
import { createTestDb, type TestDb } from "./containers.ts";

/**
 * A schema broad enough that every extractor family contributes something and
 * the families that interact do so: identity + GENERATED columns (the
 * `defaultFactIds` / shadow-edge interplay in dependencies.ts, which is the ONLY
 * cross-family read in the whole extractor), FKs, views + matviews, routines,
 * triggers, RLS policies, enums, domains, composite types, collations, rules,
 * sequences, comments, and ACL grants. `pgcrypto` covers extension membership
 * provenance cheaply.
 */
function fixtureSql(): string {
  return `
    CREATE EXTENSION IF NOT EXISTS pgcrypto;
    CREATE ROLE app_reader NOLOGIN;
    CREATE ROLE app_writer NOLOGIN;
    GRANT app_reader TO app_writer;

    CREATE SCHEMA app;
    COMMENT ON SCHEMA app IS 'application objects';

    CREATE TYPE app.status AS ENUM ('draft', 'live', 'archived');
    CREATE TYPE app.money_pair AS (low numeric, high numeric);
    CREATE DOMAIN app.positive_int AS integer CHECK (VALUE > 0);
    CREATE COLLATION app.ci (provider = icu, locale = 'und-u-ks-level2', deterministic = false);

    CREATE SEQUENCE app.legacy_counter START 100 INCREMENT 5;

    CREATE TABLE app.tenants (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      slug text NOT NULL UNIQUE,
      created_at timestamptz NOT NULL DEFAULT now()
    );
    COMMENT ON TABLE app.tenants IS 'tenant registry';
    COMMENT ON COLUMN app.tenants.slug IS 'url-safe key';

    CREATE TABLE app.documents (
      id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      tenant_id integer NOT NULL REFERENCES app.tenants (id) ON DELETE CASCADE,
      title text NOT NULL,
      -- GENERATED column: no \`default\` fact exists, so the pg_depend shadow edge
      -- onto the column is the only carrier (dependencies.ts P2)
      title_upper text GENERATED ALWAYS AS (upper(title)) STORED,
      body text DEFAULT ''::text,
      state app.status NOT NULL DEFAULT 'draft',
      weight app.positive_int DEFAULT 1,
      span app.money_pair,
      legacy integer DEFAULT nextval('app.legacy_counter'),
      CONSTRAINT documents_title_not_blank CHECK (length(title) > 0)
    );
    CREATE INDEX documents_tenant_idx ON app.documents (tenant_id);
    CREATE INDEX documents_state_live_idx ON app.documents (tenant_id)
      WHERE state = 'live';

    CREATE TABLE app.events (
      id integer GENERATED BY DEFAULT AS IDENTITY,
      document_id bigint REFERENCES app.documents (id),
      at timestamptz NOT NULL DEFAULT now(),
      -- a partitioned table's PK must cover the partition key
      PRIMARY KEY (id, at)
    ) PARTITION BY RANGE (at);
    CREATE TABLE app.events_2024 PARTITION OF app.events
      FOR VALUES FROM ('2024-01-01') TO ('2025-01-01');

    CREATE VIEW app.live_documents AS
      SELECT d.id, d.title, d.title_upper, t.slug
      FROM app.documents d JOIN app.tenants t ON t.id = d.tenant_id
      WHERE d.state = 'live';
    CREATE MATERIALIZED VIEW app.document_counts AS
      SELECT tenant_id, count(*) AS n FROM app.documents GROUP BY tenant_id;
    CREATE UNIQUE INDEX document_counts_tenant_idx
      ON app.document_counts (tenant_id);

    CREATE FUNCTION app.slugify(input text) RETURNS text
      LANGUAGE sql IMMUTABLE AS $$ SELECT lower(regexp_replace(input, '\\W+', '-', 'g')) $$;
    CREATE FUNCTION app.touch() RETURNS trigger LANGUAGE plpgsql AS $$
      BEGIN NEW.at := now(); RETURN NEW; END $$;
    CREATE PROCEDURE app.noop() LANGUAGE plpgsql AS $$ BEGIN END $$;
    CREATE AGGREGATE app.sum_positive (app.positive_int) (
      SFUNC = int4pl, STYPE = integer, INITCOND = '0'
    );

    CREATE TRIGGER events_touch BEFORE INSERT ON app.events_2024
      FOR EACH ROW EXECUTE FUNCTION app.touch();

    ALTER TABLE app.documents ENABLE ROW LEVEL SECURITY;
    CREATE POLICY documents_read ON app.documents FOR SELECT
      TO app_reader USING (state = 'live');
    CREATE POLICY documents_write ON app.documents FOR INSERT
      TO app_writer WITH CHECK (length(title) > 0);

    CREATE TABLE app.audit_sink (payload text);
    CREATE RULE audit_no_delete AS ON DELETE TO app.audit_sink DO INSTEAD NOTHING;

    GRANT USAGE ON SCHEMA app TO app_reader;
    GRANT SELECT ON app.documents TO app_reader;
    GRANT SELECT, INSERT, UPDATE ON app.documents TO app_writer;
    GRANT USAGE, SELECT ON SEQUENCE app.legacy_counter TO app_writer;
    GRANT EXECUTE ON FUNCTION app.slugify(text) TO app_reader;
  `;
}

/** The comparison surface: everything a caller can observe about an extraction,
 *  in ORDER. Fact / edge / diagnostic ordering is exactly what a completion-order
 *  merge bug would scramble, so nothing here is sorted before comparing. */
interface Observed {
  rootHash: string;
  pgVersion: string;
  facts: Fact[];
  edges: readonly DependencyEdge[];
  factBaseDiagnostics: Diagnostic[];
  diagnostics: Diagnostic[];
}

function observe(result: ExtractResult): Observed {
  return {
    rootHash: result.factBase.rootHash,
    pgVersion: result.pgVersion,
    facts: result.factBase.facts(),
    edges: result.factBase.edges,
    factBaseDiagnostics: result.factBase.diagnostics,
    diagnostics: result.diagnostics,
  };
}

/** The rejection value of `promise`, awaited (so nothing is left dangling) and
 *  asserted to have happened at all. */
async function rejection(promise: Promise<unknown>): Promise<unknown> {
  try {
    await promise;
  } catch (error) {
    return error;
  }
  throw new Error("expected the promise to reject, but it resolved");
}

/** Every checked-out client came back, and the pool never grew past its cap. */
function expectPoolDrained(pool: pg.Pool, max: number): void {
  expect(pool.waitingCount).toBe(0);
  expect(pool.totalCount).toBeLessThanOrEqual(max);
  expect(pool.idleCount).toBe(pool.totalCount);
}

let db: TestDb;

beforeAll(async () => {
  db = await createTestDb("parallel-extract");
  await db.pool.query(fixtureSql());
}, 180_000);

afterAll(async () => {
  await db.pool.query(`DROP OWNED BY app_writer`).catch(() => {});
  await db.drop();
  await db.cluster.adminPool
    .query(`DROP ROLE IF EXISTS app_writer, app_reader`)
    .catch(() => {});
});

describe("extract: bounded-parallel extraction", () => {
  test("concurrency 2 and 4 reproduce the serial extraction exactly", async () => {
    const serial = observe(await extract(db.pool));
    // sanity: the fixture really does exercise the whole extractor
    expect(serial.facts.length).toBeGreaterThan(100);
    expect(serial.edges.length).toBeGreaterThan(100);

    for (const concurrency of [2, 4]) {
      const parallel = observe(await extract(db.pool, { concurrency }));
      expect(parallel.rootHash).toBe(serial.rootHash);
      expect(parallel.pgVersion).toBe(serial.pgVersion);
      expect(parallel.facts).toEqual(serial.facts);
      expect(parallel.edges).toEqual(serial.edges);
      expect(parallel.factBaseDiagnostics).toEqual(serial.factBaseDiagnostics);
      expect(parallel.diagnostics).toEqual(serial.diagnostics);
    }
  }, 180_000);

  test("concurrency 4 actually opens extra streams on the pool", async () => {
    // The behavioral claim behind the option: more than one catalog-query stream
    // is genuinely in flight, so the pool has to hand out more than the single
    // coordinator client. A serial extraction can never make this true.
    const pool = new pg.Pool({ connectionString: db.uri, max: 5 });
    pool.on("error", () => {});
    let peakTotal = 0;
    const sampler = setInterval(() => {
      peakTotal = Math.max(peakTotal, pool.totalCount);
    }, 2);
    try {
      await extract(pool, { concurrency: 4 });
    } finally {
      clearInterval(sampler);
    }
    expect(peakTotal).toBeGreaterThanOrEqual(2);
    expect(pool.totalCount).toBe(4);
    expectPoolDrained(pool, 5);
    await pool.end();
  }, 180_000);

  test("concurrency above the pool cap completes without deadlocking", async () => {
    // `pg.Pool.connect()` QUEUES when the pool is exhausted, and the coordinator
    // holds one client for the whole extraction — asking for more clients than
    // the pool can give would wait forever. Clamping to the pool's own max is
    // what makes this terminate.
    const pool = new pg.Pool({ connectionString: db.uri, max: 5 });
    pool.on("error", () => {});
    const serial = observe(await extract(db.pool));
    const result = observe(await extract(pool, { concurrency: 8 }));
    expect(result.rootHash).toBe(serial.rootHash);
    expect(result.facts).toEqual(serial.facts);
    expect(result.edges).toEqual(serial.edges);
    expect(result.diagnostics).toEqual(serial.diagnostics);
    expectPoolDrained(pool, 5);
    await pool.end();
  }, 180_000);

  test("a max:1 pool degrades to serial instead of hanging", async () => {
    const pool = new pg.Pool({ connectionString: db.uri, max: 1 });
    pool.on("error", () => {});
    const serial = observe(await extract(db.pool));
    const result = observe(await extract(pool, { concurrency: 4 }));
    expect(result.rootHash).toBe(serial.rootHash);
    expect(result.facts).toEqual(serial.facts);
    expect(result.edges).toEqual(serial.edges);
    // silent degradation: no new diagnostic tells the caller it went serial
    expect(result.diagnostics).toEqual(serial.diagnostics);
    expectPoolDrained(pool, 1);
    await pool.end();
  }, 180_000);

  test("a failing family rejects and releases every client", async () => {
    const pool = new pg.Pool({ connectionString: db.uri, max: 5 });
    pool.on("error", () => {});
    // Poison ONE family's catalog query (policies) on whichever stream happens
    // to run it. The rest of the streams are mid-query when it blows up, so this
    // is the "worker fails while others are in flight" cleanup path.
    const boom = new Error("poisoned pg_policy read");
    const realConnect = pool.connect.bind(pool);
    // oxlint-disable-next-line no-explicit-any -- test double, narrow on purpose
    (pool as any).connect = async () => {
      const client = await realConnect();
      const realQuery = client.query.bind(client);
      // oxlint-disable-next-line no-explicit-any -- passthrough test double
      (client as any).query = (...args: any[]) => {
        if (typeof args[0] === "string" && args[0].includes("pg_policy")) {
          return Promise.reject(boom);
        }
        // oxlint-disable-next-line no-explicit-any -- passthrough test double
        return (realQuery as any)(...args);
      };
      return client;
    };

    expect(await rejection(extract(pool, { concurrency: 4 }))).toBe(boom);
    expectPoolDrained(pool, 5);
    // and the released clients are genuinely usable — no transaction left open
    const probe = await realConnect();
    expect((await probe.query("SELECT 1 AS ok")).rows[0]).toEqual({ ok: 1 });
    probe.release();
    await pool.end();
  }, 180_000);

  test("ExtractionTimeoutError still surfaces from a worker stream", async () => {
    let err: unknown;
    try {
      await extract(db.pool, { concurrency: 4, statementTimeoutMs: 1 });
    } catch (e) {
      err = e;
    }
    expect(err).toBeInstanceOf(ExtractionTimeoutError);
    const timeout = err as ExtractionTimeoutError;
    expect(timeout.timeoutMs).toBe(1);
    expect(timeout.queryLabel.length).toBeGreaterThan(0);
    expectPoolDrained(db.pool, 5);
  }, 180_000);

  test("concurrency 1 and undefined are the same path", async () => {
    const serial = observe(await extract(db.pool));
    const one = observe(await extract(db.pool, { concurrency: 1 }));
    expect(one.rootHash).toBe(serial.rootHash);
    expect(one.facts).toEqual(serial.facts);
    expect(one.edges).toEqual(serial.edges);
    expect(one.diagnostics).toEqual(serial.diagnostics);
    expectPoolDrained(db.pool, 5);
  }, 180_000);

  test("a nonsense concurrency is rejected loudly", async () => {
    for (const bad of [0, -1, 2.5, Number.NaN, Number.POSITIVE_INFINITY]) {
      const error = await rejection(extract(db.pool, { concurrency: bad }));
      expect((error as Error).message).toMatch(/concurrency/i);
    }
    expectPoolDrained(db.pool, 5);
  }, 60_000);
});
