DO $$ BEGIN CREATE ROLE corpus_mrg_anon NOLOGIN; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE ROLE corpus_mrg_authenticated NOLOGIN; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE ROLE corpus_mrg_service NOLOGIN; EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE SCHEMA app;

-- the "fresh Supabase-style table" shape: identity PK, RLS enabled, and the
-- same full privilege set granted to several roles. Exercises the co-create
-- compaction stack end-to-end (PK fold + multi-grantee GRANT merge) in both
-- compact modes, both directions.
CREATE TABLE app.notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE app.notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.notes ADD CONSTRAINT notes_pkey PRIMARY KEY (id);
GRANT ALL ON TABLE app.notes TO corpus_mrg_anon;
GRANT ALL ON TABLE app.notes TO corpus_mrg_authenticated;
GRANT ALL ON TABLE app.notes TO corpus_mrg_service;
