CREATE SCHEMA app;

-- Same identity column, non-default parameters: the forward diff must emit
-- in-place ALTER TABLE … ALTER COLUMN … SET INCREMENT BY / START WITH / CACHE /
-- CYCLE. Before the options were extracted these hashed identically and the
-- diff was empty.
CREATE TABLE app.altered (
  id integer GENERATED ALWAYS AS IDENTITY (START WITH 500 INCREMENT BY 10 CACHE 20 CYCLE),
  name text
);

-- A freshly created identity column carrying non-default parameters, to
-- exercise the GENERATED … AS IDENTITY (…) render in the create path.
CREATE TABLE app.created (
  id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 7 MINVALUE 100 MAXVALUE 9999),
  label text
);
